const productsDB = [
  {
    id: 1,
    name: "Smartphone",
    brand: "TechOne",
    model: "X200",
    price: 699.99,
    features: ["5G", "128GB Storage", "Triple Camera"],
    isAvailable: true,
  },
  {
    id: 2,
    name: "Laptop",
    brand: "UltraComp",
    model: "Pro 15",
    price: 1199.99,
    specs: {
      ram: "16GB",
      storage: "512GB SSD",
      processor: "Intel i7",
    },
    isAvailable: false,
  },
  {
    id: 3,
    name: "Smartwatch",
    brand: "FitGear",
    model: "Tracker 4",
    price: 199.99,
    features: ["Heart Rate Monitor", "GPS", "Water Resistant"],
    isAvailable: true,
  },
  {
    id: 4,
    name: "Tablet",
    brand: "ScreenTab",
    model: "Tab X",
    price: 499.99,
    specs: {
      screen: "10.1 inch",
      storage: "256GB",
      battery: "6000mAh",
    },
    isAvailable: true,
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    brand: "SoundWave",
    model: "Boom 2",
    price: 149.99,
    features: ["Waterproof", "12-hour battery life", "360° sound"],
    isAvailable: false,
  },
  {
    id: 6,
    name: "Headphones",
    brand: "AudioBlast",
    model: "NoiseMax",
    price: 249.99,
    features: ["Noise Cancelling", "Bluetooth", "30-hour battery"],
    isAvailable: true,
  },
  {
    id: 7,
    name: "Gaming Console",
    brand: "PlayFun",
    model: "Xtreme 5",
    price: 499.99,
    features: ["4K gaming", "VR compatible", "500GB Storage"],
    isAvailable: false,
  },
  {
    id: 8,
    name: "Smart TV",
    brand: "VisionPro",
    model: "Ultra HD 55",
    price: 799.99,
    specs: {
      screenSize: "55 inch",
      resolution: "4K",
      smartFeatures: ["Netflix", "YouTube", "Voice Control"],
    },
    isAvailable: true,
  },
  {
    id: 9,
    name: "Drone",
    brand: "FlyTech",
    model: "AirMaster 300",
    price: 399.99,
    features: ["4K Camera", "30 min flight time", "GPS"],
    isAvailable: true,
  },
  {
    id: 10,
    name: "Wireless Charger",
    brand: "PowerHub",
    model: "FastCharge Pro",
    price: 59.99,
    features: ["Fast Charging", "Qi Certified", "LED indicator"],
    isAvailable: true,
  },
];

export default productsDB;
